### ISSUE TITLE
Periodic crashes in bok

### ISSUE THREAD

**Issue by kheimerl** [endaga/openbts#46]
Potentially related to sdcch traffic, see matt's email.

**Comment by kheimerl** [comment]
(gdb) bt full
#0  0xb765245f in ?? ()
No symbol table info available.
#1  0xb3736940 in ?? ()
No symbol table info available.
#2  0x08324f3d in UnixSignal::Handler (this=0x843be80 <gSigVec>, 
    sig=sig@entry=11) at UnixSignal.cpp:68
        buf = "core.openbts", '\000' <repeats 548 times>...
#3  0x083254e2 in _sigHandler (sig=11) at UnixSignal.cpp:49
        __FUNCTION__ = "_sigHandler"
#4  <signal handler called>
No symbol table info available.
#5  0x0831f96b in BitVector::peekField (this=this@entry=0xb3d00468, 
    readIndex=readIndex@entry=8, length=length@entry=8) at BitVector.cpp:65
        i = 0
        accum = 0
        dp = 0x9 <error: Cannot access memory at address 0x9>
#6  0x081f2288 in GSM::L3Frame::MTI (this=0xb3d00468) at GSMTransfer.cpp:635
        mti = <optimized out>
        this = 0xb3d00468
#7  0x081f23f0 in GSM::L3Frame::text (this=this@entry=0xb3d00468, os=...)
    at GSMTransfer.cpp:56
        mtiname = {static npos = <optimized out>, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<cha---Type <return> to continue, or q <return> to quit---
r>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0xb373b148 "\314\vC\b\350\fC\b\305\020\001\264\305\020\001\264\305\020\001\264\304\020\001\264z\021\001\264\304\022\001\264\264\001_\267\020"}}
#8  0x081f26c4 in GSM::operator<< (os=..., frame=...) at GSMTransfer.cpp:66
No locals.
#9  0x082ad5b7 in csl3HandleFrame (lch=<optimized out>, frame=<optimized out>)
    at L3StateMachine.cpp:606
        deleteit = <optimized out>
        l3msg = <optimized out>
        mmchan = <optimized out>
#10 Control::checkemMessages (dcch=dcch@entry=0x959ee50, delay=delay@entry=100)
    at L3StateMachine.cpp:771
        l3frame = <optimized out>
        __FUNCTION__ = "checkemMessages"
        set = <optimized out>
#11 0x082b2968 in L3SDCCHLoop (dcch=<optimized out>) at L3StateMachine.cpp:972
No locals.
#12 Control::L3DCCHLoop (dcch=0x959ee50, frame=0xb3d148b0)
    at L3StateMachine.cpp:1003
        prim = GSM::L3_ESTABLISH_INDICATION
        __FUNCTION__ = "L3DCCHLoop"
        __PRETTY_FUNCTION__ = "void Control::L3DCCHLoop(Control::L3LogicalChanne---Type <return> to continue, or q <return> to quit---
l*, GSM::L3Frame*)"
#13 0x082ed9fc in Control::DCCHDispatcher (DCCH=DCCH@entry=0x959ee50)
    at DCCHDispatch.cpp:56
        frame = <optimized out>
        __FUNCTION__ = "DCCHDispatcher"
#14 0x08329e77 in thread_main (arg=0x9573d58) at Threads.cpp:292
        p = 0x9573d58
        task = 0x82ed100 <Control::DCCHDispatcher(Control::L3LogicalChannel*)>
        param = 0x959ee50
#15 0xb748ef70 in ?? ()
No symbol table info available.
#16 0x09573d58 in ?? ()
No symbol table info available.
#17 0xb73c5bee in ?? ()
No symbol table info available.

**Comment by kheimerl** [comment]
Seems like a relatively simple crash actually; we note a frame can't be parsed, we then try to print it by parsing it and it explodes.

**Comment by kheimerl** [comment]
Fixed in https://github.com/endaga/openbts/tree/bok_l3_segfault, other issues continue.
