### ISSUE TITLE
Crash in bok:

### ISSUE THREAD

**Issue by kheimerl** [endaga/openbts#49]
#0  0xb765645f in ?? ()
No symbol table info available.
#1  0xb35aa7c0 in ?? ()
No symbol table info available.
#2  0x0832533d in UnixSignal::Handler (this=0x843ae80 <gSigVec>, 
    sig=sig@entry=11) at UnixSignal.cpp:68
        buf = "core.openbts", '\000' <repeats 8179 times>
#3  0x083258e2 in _sigHandler (sig=11) at UnixSignal.cpp:49
        __FUNCTION__ = "_sigHandler"
#4  <signal handler called>
No symbol table info available.
#5  0xb7495036 in ?? ()
No symbol table info available.
#6  0x55c70006 in ?? ()
No symbol table info available.
#7  0x0009bfd2 in ?? ()
No symbol table info available.
#8  0x55c70006 in ?? ()
No symbol table info available.
#9  0xb35aef38 in ?? ()
No symbol table info available.
#10 0x08345825 in ScopedLock (wMutex=..., this=<synthetic pointer>)
    at Threads.h:171
#11 Utils::RefCntBase::incRefCnt (this=0x636e6176) at Utils.cpp:62
        lock = {mMutex = @0x636e617a}
        __FUNCTION__ = "incRefCnt"
        __PRETTY_FUNCTION__ = "void Utils::RefCntBase::incRefCnt() const"
#12 0x082c18fa in rcInc (this=0xb35af0dc) at ../CommonLibs/Utils.h:237
No locals.
#13 RefCntPointer (other=..., this=0xb35af0dc) at ../CommonLibs/Utils.h:243
No locals.
#14 Control::MMContext::mmGetTran (this=0xb2e6ebe0, ati=0) at L3MMLayer.cpp:819
        lock = {mMutex = @0x843aaa0}
#15 0x082c3d63 in Control::MMContext::mmCheckSipMsgs (
    this=this@entry=0xb2e6ebe0) at L3MMLayer.cpp:285
        tranp = {rcPointer = 0x636e6172}
        i = 0
        result = false
#16 0x082ad338 in Control::checkemMessages (dcch=dcch@entry=0x88276f8, 
    delay=delay@entry=20) at L3StateMachine.cpp:802
        __FUNCTION__ = "checkemMessages"
        set = 0xb2e6ebe0
#17 0x082b33de in l3CallTrafficLoop (dcch=<optimized out>)
    at L3StateMachine.cpp:900
        rtran = {rcPointer = 0x0}
        tran = 0x0
        needReports = <optimized out>
        nextDelay = <optimized out>
        fCount = <optimized out>
        alternate = 409
#18 Control::L3DCCHLoop (dcch=0x88276f8, frame=0xb2f9a2d8)
    at L3StateMachine.cpp:1006
        prim = <optimized out>
        __FUNCTION__ = "L3DCCHLoop"
        __PRETTY_FUNCTION__ = "void Control::L3DCCHLoop(Control::L3LogicalChannel*, GSM::L3Frame*)"
#19 0x082eddfc in Control::DCCHDispatcher (DCCH=DCCH@entry=0x88276f8)
    at DCCHDispatch.cpp:56
        frame = <optimized out>
        __FUNCTION__ = "DCCHDispatcher"
#20 0x0832a277 in thread_main (arg=0x87e42f0) at Threads.cpp:292
        p = 0x87e42f0
        task = 0x82ed500 <Control::DCCHDispatcher(Control::L3LogicalChannel*)>
        param = 0x88276f8
#21 0xb7492f70 in ?? ()
No symbol table info available.
#22 0x087e42f0 in ?? ()
No symbol table info available.

**Comment by kheimerl** [comment]
This is almost totally useless. Failed in the lock itself somehow?
